--Bizimle payalşılan veriler incelediğimde 3 adet tablonun tasarlanması yereterlidir

--------------------------------------------TARIFFS TABLE and INDEXES---------------------------------------------------------------------------
--Ilk olarak TARIFFS tablosu oluşturulmalıdır. Cünkü Customers tablosunda tanımlanacak Foreıgn keyin bu tabloyu referans alması gerekiyor.
--Bu tablonun herhangi bir foreıgn key içermemesi de bu tablonun ilk olarak oluşturulabilecğinin de göstergesidir.
--Bu tabloda TARIFF_ID Primary Key olarak tanımlanabilecek en doğru sütündür.
--Tabloda ki bazı sayı değerlerinin 8 basamaklı olarak kısıtalanması hem belleği iyi yönetmekte hem de normal olamayan büyüklükte sayı girişini engellemektedir.
CREATE TABLE TARIFFS (
TARIFF_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
TARIFF_NAME VARCHAR2(50)NOT NULL,
MONTHLY_FEE NUMBER(8),
DATA_LIMIT NUMBER(8),
MINUTE_LIMIT NUMBER(8),
SMS_LIMIT NUMBER(8)
);



--------------------------------------------CUSTOMERS TABLE and INDEXES---------------------------------------------------------------------------
--Ikinci olarak bu tablo oluşturulmalıdır. Sebebi ise bu tablodaki TARIFF_ID sütunun referans olarak TARIFFS tablosundaki TARIFF_ID sütunu referans olarak alması.
--Eğer TARIFFS tablosu oluşturulmadan bu tablo oluşursa refeansı bulamayacağı için tablo hata vericek ve oluşmayacaktır 
--Burada CUSTOMER_NAME NOT NULL olarak tanımlanmıştır.Müşterinin ismi olmadan veri girmek çok mantıklı değildir.
CREATE TABLE CUSTOMERS(
CUSTOMER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
CUSTOMER_NAME VARCHAR2(40) NOT NULL,
CITY VARCHAR2(40),
SIGNUP_DATE DATE,
TARIFF_ID NUMBER REFERENCES TARIFFS(TARIFF_ID)
);


--FOREIGN KEY indekslenmedlidir.
--Bu müşterilerin tarifelerini hızlıca eşleşmesini sağlar.
--Index adının IDX ile başlaması kullanılan br standarttır.
CREATE INDEX IDX_CUSTOMERS_TARIFF_ID 
ON CUSTOMERS (TARIFF_ID);

--Bizden istenilenler incelendiğinde "En eski /En yeni kullanıcıyı bulmak gibi" müşterinin kayıt tarihini içeren çok fazla sorgu yaptğımız için
--bu sütun indexlenmelidir. Bu indeksleme istenilen tarihi bulma hızımızı artıracaktır.
--Index adının IDX ile başlaması kullanılan br standarttır.
CREATE INDEX IDX_CUSTOMERS_SIGNUP_DATE 
ON CUSTOMERS (SIGNUP_DATE);

--Bizden istenilenler incelendiğinde şehirlere göre dağılım yapma gibi müşterin yaşadığı şehir içeren çok fazla sorgu yaptğımız için
--bu sütun indexlenmelidir. Bu indeksleme istenilen şehri bulma hızımızı artıracaktır.
--Index adının IDX ile başlaması kullanılan br standarttır.
CREATE INDEX IDX_CUSTOMERS_CITY 
ON CUSTOMERS (CITY);




--------------------------------------------MONTHLY_USAGES TABLE and INDEXES---------------------------------------------------------------------------
--Ucuncu olarak bu tablo oluşturulmalıdır. Sebebi ise bu tablodaki CUSTOMER_ID sütunun referans olarak CUSTOMERS tablosundaki CUSTOMER_ID sütunu referans olarak alması.
--Aynı şekilde diğer iki tablo sırayla oluşturulmadan bu tablo oluşturlamaz.
--Burada PAYMENT_STATUS üç farklı veri içerimelidir .Bu sütun 'LATE','PAID','UNPAID' dışında başka veri almayacak şekilde tasarlanmıştır.
--NUMBER (12,2) şeklinde kullanmak bizim için bu sayıda virgülden sonra maksimum iki basamak olacağı anlamına gelmektedir.
CREATE TABLE MONTHLY_USAGES (
USAGE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
DATA_USAGE NUMBER (12,2),
MINUTE_USAGE NUMBER (8),
SMS_USAGE NUMBER (8),
PAYMENT_STATUS VARCHAR2(6) CHECK (PAYMENT_STATUS IN ('LATE','PAID','UNPAID')),
CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID)
);


--FOREIGN KEY indekslenmedlidir.
--Bu aylık kullanımların müşterilerle hızlıca eşleşmesini sağlar.
--Index adının IDX ile başlaması kullanılan br standarttır.
CREATE INDEX IDX_USAGES_CUSTOMER_ID 
ON MONTHLY_USAGES (CUSTOMER_ID);





--5 Kullanım Analizi için bir view oluşturalmaldır.
--5.1 ve 5.2' deki sorgularda bu viewi kullancağız.
--WITH kullanmayıp bir VİEW oluşturmamızın sebebi bu wiewi birçok kez kullanıp üzerinde farklı işlemler yapıyor olmamız.
--Bu wiew kullanım bilgileri için farkıl işlemlerde kullanılabileceği için kullanımlarla ilgili büütn sütunları bu viewe ekledik.
--CREATE OR REPLACE ile başlamızın sebebi ise view bir kere oluştukdan sonra bize view üzerinde değşiklik yapma esnekliğni kazandırmasıdır.
CREATE OR REPLACE VIEW  V_USAGE_INFORMATION AS 
SELECT c.CUSTOMER_NAME, t.TARIFF_NAME, t.DATA_LIMIT, m.DATA_USAGE, t.MINUTE_LIMIT, m.MINUTE_USAGE, t.SMS_LIMIT, m.SMS_USAGE 
FROM CUSTOMERS c
JOIN TARIFFS t ON c.TARIFF_ID = t.TARIFF_ID    
JOIN MONTHLY_USAGES  m ON c.CUSTOMER_ID = m.CUSTOMER_ID;





